[2025-08-14 14:08:16,963] WARNING django.request - Not Found: /
[2025-08-14 14:08:16,965] WARNING django.server - "GET / HTTP/1.1" 404 5904
[2025-08-14 15:21:40,639] ERROR django.request - Internal Server Error: /opportunity_detail/
Traceback (most recent call last):
  File "C:\Users\orhan.metin.BIM\lk\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\orhan.metin.BIM\lk\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OpportunityDetail() missing 1 required positional argument: 'opportunity_id'
[2025-08-14 15:21:40,643] ERROR django.server - "GET /opportunity_detail/ HTTP/1.1" 500 62684
[2025-08-14 15:36:07,195] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 15:36:07,197] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 15:37:50,246] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 15:37:50,247] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 15:38:56,133] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 15:38:56,133] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 15:38:56,718] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 15:38:56,720] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 15:38:58,006] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 15:38:58,008] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 15:39:47,787] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 15:39:47,788] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 15:53:33,942] WARNING django.request - Not Found: /urunlercompany/test
[2025-08-14 15:53:33,943] WARNING django.server - "GET /urunlercompany/test HTTP/1.1" 404 6257
[2025-08-14 15:53:48,893] WARNING django.request - Not Found: /urunlercompany/test
[2025-08-14 15:53:48,895] WARNING django.server - "GET /urunlercompany/test HTTP/1.1" 404 6257
[2025-08-14 15:53:51,428] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 15:53:51,429] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 15:54:58,414] WARNING django.request - Not Found: /pass/
[2025-08-14 15:54:58,416] WARNING django.server - "GET /pass/ HTTP/1.1" 404 6215
[2025-08-14 15:56:02,202] WARNING django.request - Not Found: /pass/
[2025-08-14 15:56:02,244] WARNING django.server - "GET /pass/ HTTP/1.1" 404 6215
[2025-08-14 16:03:27,380] WARNING django.request - Not Found: /pass/
[2025-08-14 16:03:27,381] WARNING django.server - "GET /pass/ HTTP/1.1" 404 6215
[2025-08-14 16:03:29,556] WARNING django.request - Not Found: /pass/
[2025-08-14 16:03:29,557] WARNING django.server - "GET /pass/ HTTP/1.1" 404 6215
[2025-08-14 16:03:56,567] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 16:03:56,568] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 16:04:15,336] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 16:04:15,338] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 16:04:27,044] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 16:04:27,045] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 16:06:12,343] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 16:06:12,343] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 16:06:14,554] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 16:06:14,556] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 16:06:31,911] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 16:06:31,912] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 16:06:48,534] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 16:06:48,535] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 16:07:06,706] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 16:07:06,707] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 16:07:19,046] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 16:07:19,046] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
[2025-08-14 16:07:32,906] WARNING django.request - Not Found: /favicon.ico
[2025-08-14 16:07:32,908] WARNING django.server - "GET /favicon.ico HTTP/1.1" 404 6233
